apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-env-config
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
