apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-helm
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/helm/releases/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
