namespace: staging-helm-ns

replicaCount: 

image:
  repository: nginx
  tag: stable

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

indexHtml: |
  <html>Hey, I'm deployed on staging cluster!!</html>

env:
  ENVIRONMENT: staging
  LOG_LEVEL: info

service:
  port: 80
  targetPort: 80